const sport = [{
        name: "Lewis Hamilton",
        picture: 'images/Lewis.jpg',
        biography: 'https://en.wikipedia.org/wiki/Lewis_Hamilton',
        birthDate: '07/01/1985',
        birthPlace: 'Stevenage ',
        country: 'England',
        spouse: " not married ",
        children: " no children",
        competitionLeague: 'Formula1',
        Team: 'Merceds AMG Patronas',
        championships: ' 7 championships ',
    },
    {
        name: "Kobe Bryant",
        picture: 'images/bryant.jpg',
        biography: 'https://en.wikipedia.org/wiki/Kobe_Bryant',
        birthDate: '23/08/1978',
        birthPlace: 'Philadelphie, Pennsylvanie',
        country: 'United States of America',
        spouse: " was married with Vanessa Bryant",
        children: ' four children : ' + [' Gianna Maria-Onore Bryant', ' Natalia Diamante Bryant ',
            ' Bianka Bella Bryant ', ' Capri Kobe Bryant '
        ],
        competitionLeague: 'NBA',
        Team: 'Los Angeles Lakers',
        championships: ' 5 NBA championships ',

    },
    {
        name: 'Cristiano Ronaldo',
        picture: 'images/cr7.jpg',
        biography: 'https://en.wikipedia.org/wiki/Cristiano_Ronaldo',
        birthDate: '05/02/1985',
        birthPlace: 'Hospital Dr. Nélio Mendonça, Funchal',
        country: 'Portugal',
        spouse: ' in relation with Georgina Rodriguez',
        children: ' four children : ' + [' Cristiano Jr', ' Alana Martina dos Santos Aveiro ', ' Eva Maria Dos Santos ', ' Mateo Ronaldo '],
        competitionLeague: 'Premier League',
        Team: 'Manchester United',
        championships: [' 5 golden ball ', ' 6 championships ', ' 5 uefa cl ', ' 1 european champion ', ' 1 european nations league champion '],
    },
    {
        name: 'Serena Williams',
        picture: 'images/williams.webp',
        biography: 'https://en.wikipedia.org/wiki/Serena_Williams',
        birthDate: '26/09/1981',
        birthPlace: 'Saginaw, Michigan',
        country: 'United States of America',
        spouse: ' married with Alexis Ohanian',
        children: ' one child :  Alexis Olympia Ohanian Jr',
        competitionLeague: 'Tennis',
        Team: 'USA national team',
        championships: '23 Grand Chelem',

    },
    {
        name: 'Lionel Messi',
        picture: 'images/lionel.jpeg',
        biography: 'https://en.wikipedia.org/wiki/Lionel_Messi',
        birthDate: '24/06/1987',
        birthPlace: ' Rosario ',
        country: ' Argentina ',
        spouse: ' married with Antonella Roccuzzo ',
        children: ' three children : ' + [' Mateo Messi Roccuzzo ', ' Ciro Messi Roccuzzo ', ' Thiago Messi'],
        competitionLeague: ' Ligue 1 ',
        Team: ' Paris Saint Germain ',
        championships: [' 6 golden balls ', ' 10 championships ', ' 4 uefa cl ', ' 1 South American championship '],

    },
    {
        name: 'Usain Bolt',
        picture: 'images/bolt.jpg',
        biography: 'https://en.wikipedia.org/wiki/Usain_Bolt',
        birthDate: '21/08/1986',
        birthPlace: 'Sherwood Content',
        country: 'Jamaica .',
        spouse: ' in relation with Kasi Bennett',
        children: ' three children : ' + ['Olympia Lightning Bolt', 'Thunder Bolt', 'Saint Leo Bolt'],
        competitionLeague: 'Athletisme, sprint',
        Team: 'Jamaican National Team',
        championships: '8 olympic gold medals',

    },
    {
        name: 'Roger Federer',
        picture: 'images/federer.jpg',
        biography: 'https://en.wikipedia.org/wiki/Roger_Federer',
        birthDate: '21/08/1981',
        birthPlace: 'Bâle',
        country: 'Switzeland',
        spouse: ' married with Miroslava Vavrinec ',
        children: ' four children : ' + [' Myla Rose Federer ', ' Lennart Federer ', ' Leo Federer', ' Charlene Riva Federer '],
        competitionLeague: 'Tennis',
        Team: 'Swiss National Team',
        championships: ' 20 Grand Chelem ',

    },
    {
        name: "Lebron James",
        picture: 'images/lebron.jpg',
        biography: 'https://en.wikipedia.org/wiki/LeBron_James',
        birthDate: '30/12/1984',
        birthPlace: ' Akron, Ohio',
        country: 'United States of America',
        spouse: " married with Savannah James ",
        children: ' three children : ' + [' LeBron James Jr.', 'Bryce Maximus James', 'Zhuri James'],
        competitionLeague: 'NBA',
        Team: 'Los Angeles Lakers',
        championships: '4 NBA chamionships',

    },
    {
        name: 'Ronaldinho',
        picture: 'images/ronaldinho.jpg',
        biography: 'https://en.wikipedia.org/wiki/Ronaldinho',
        birthDate: '21/03/1980',
        birthPlace: 'Porto Alegre, Rio Grande do Sul',
        country: 'Brazil',
        spouse: ' not married ',
        children: ' one child João de Assis Moreira',
        competitionLeague: ' Ligua ',
        Team: 'Fc Barcelona',
        championships: ['1 golden ball ', ' 2 championships ', ' 2 uefa cl ', ' 1 South American championship ', ' and 1 world cup champion'],

    },
    {
        name: 'Rafael Nadal',
        picture: 'images/nadal.jpg',
        biography: 'https://en.wikipedia.org/wiki/Rafael_Nadal',
        birthDate: '03/06/1986',
        birthPlace: 'Manacor',
        country: 'Spain',
        spouse: ' married with Xisca Perello',
        children: ' no children ',
        competitionLeague: 'Tennis',
        Team: 'Spanish National Team',
        championships: '20 Grand Chelem',

    },
];